# Generated by Django 4.1.5 on 2023-02-03 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apischool', '0002_student_teacher_age_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='Teacher',
        ),
        migrations.AddField(
            model_name='teacher',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher', to='apischool.course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(related_name='courses', to='apischool.student'),
        ),
    ]
