# Generated by Django 4.1.5 on 2023-02-17 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apischool', '0004_remove_teacher_course_course_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='quantity',
        ),
    ]
